/**
  ******************************************************************************
  * @file    main.c
  * @author  Auto-generated by STM32CubeIDE
  * @version V1.0
  * @brief   Default main function.
  ******************************************************************************
*/
#include "servo.h"

u32 G_u32OnTime_EN;
u32 G_u32OffTime_EN;

u32 G_u32OnTime_EX;
u32 G_u32OffTime_EX;

void Generate_PWM_Exit(u16 Copy_u16DutyCyclePercentx10, u32 Copy_u32PeriodInMilli)
{
	u8 Copy_ChoosePin = 14; 
	//Percentage of duty times 10 to handle the floating numbers
	G_u32OnTime_EX = (Copy_u16DutyCyclePercentx10 * Copy_u32PeriodInMilli); 
	G_u32OffTime_EX = (Copy_u32PeriodInMilli*1000) - G_u32OnTime;
	//G_u8PinNum = Copy_ChoosePin;
	MSTK_vPeriodicInterval(G_u32OffTime_EX , ON_PWM);
}

void ON_PWM_Exit(void)
{
	/* Pin (14) >> EXIT  -- Pin (15) >> Enter*/
	MGPIO_vWriteData( _GPIOA_PORT, 14, 1u);  
	MSTK_vPeriodicInterval(G_u32OnTime_EX, OFF_PWM);
}

void OFF_PWM_Exit(void)
{
	/* Pin (14) >> EXIT  -- Pin (15) >> Enter*/
	MGPIO_vWriteData(  _GPIOA_PORT , 14,0u);
	MSTK_vPeriodicInterval(G_u32OffTime_EX , ON_PWM);
}

// set nedded angel //used
void Servo_angle_Exit(u16 angle)
{	
	switch (angle)
	{
		case 90 :
		Generate_PWM(90, 20);	// angle 90 //-67
		break;
		case 0 :
		Generate_PWM(-300, 20);	// angle 0  +90
		break;
		case 180 :
		Generate_PWM( 300, 20);	// angle 180  -90
		break;
	}
}
//////////////////////////////////////////////////////////////////////////////////////////////////////

void Generate_PWM_Enter(u16 Copy_u16DutyCyclePercentx10, u32 Copy_u32PeriodInMilli)
{
	u8 Copy_ChoosePin = 15; 
	//Percentage of duty times 10 to handle the floating numbers
	G_u32OnTime_EN = (Copy_u16DutyCyclePercentx10 * Copy_u32PeriodInMilli); 
	G_u32OffTime_EN = (Copy_u32PeriodInMilli*1000) - G_u32OnTime;
	//G_u8PinNum = Copy_ChoosePin;
	MSTK_vPeriodicInterval(G_u32OffTime_EN , ON_PWM);
}

void ON_PWM_Enter(void)
{
	/* Pin (14) >> EXIT  -- Pin (15) >> Enter*/
	MGPIO_vWriteData( _GPIOA_PORT, 15, 1u);  
	MSTK_vPeriodicInterval(G_u32OnTime_EN, OFF_PWM);
}

void OFF_PWM_Enter(void)
{
	/* Pin (14) >> EXIT  -- Pin (15) >> Enter*/
	MGPIO_vWriteData(  _GPIOA_PORT , 15,0u);
	MSTK_vPeriodicInterval(G_u32OffTime_EN , ON_PWM);
}

// set nedded angel // used
void Servo_angle_Enter(u16 angle)
{	
	switch (angle)
	{
		case 90 :
		Generate_PWM(90, 20);	// angle 90 //-67
		break;
		case 0 :
		Generate_PWM(-300, 20);	// angle 0  +90
		break;
		case 180 :
		Generate_PWM( 300, 20);	// angle 180  -90
		break;
	}
}